[package]
name = "obsidian_fast_create"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
glib = "0.18.3"
gtk4 = "0.7.3"
gtk4-macros = "0.7.2"

